config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  resources :leads do 
    resources :engages, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
  
  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/engage.rb
class Engage < ApplicationRecord
  belongs_to :user
  belongs_to :lead
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
  enum status: [:fp, :fu, :bs, :ros, :closed] 
  has_one :engage
  
  after_initialize do 
    if self.new_record? 
      self.status ||= :fp
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  enum role: [:sales, :admin]
  has_many :authentications, dependent: :destroy
  has_many :leads
  has_many :engages

  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = self.create!(
      first_name: auth_hash["info"]["first_name"],
      last_name: auth_hash["info"]["last_name"],
      email: auth_hash["info"]["email"],
      password: SecureRandom.hex(10)
    )
    user.authentications << authentication
    return user
  end
 
  # grab google to access google for user data
  def google_token
    x = self.authentications.find_by(provider: 'google_oauth2')
    return x.token unless x.nil?
  end

  after_initialize do 
    if self.new_record? 
      self.role ||= :sales 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/engages_controller.rb
class EngagesController < ApplicationController
     def new
        @lead = Lead.find(params[:lead_id])
        @engage = Engage.new
    end

    def create
        engage = Engage.new
        engage.user_id = current_user.id 
        engage.lead_id = params[:lead_id]
        # byebug
        if engage.save 
            flash[:notice] = "Engage Saved!"
            redirect_to lead_path(params[:lead_id])
        else
            flash[:notice] = "Engage Failed to Save!"
            redirect_to leads_path
        end
    end

    def destroy 
        engage = Engage.find_by(lead_id: params[:lead_id], user_id: params[:id])
        engage.destroy
        flash[:notice] = "Engage Removed"
        redirect_to lead_path(params[:lead_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login
  
  def index
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
    def index
        @leads = Lead.all
    end

    def new 
        @lead = Lead.new
    end

    def create
        lead = Lead.new(lead_params)
        lead.user_id = current_user.id
        if lead.save
            flash[:notice] = "Lead Saved!"
            redirect_to lead
        else
            flash[:error] = "Lead didn't save!"
            redirect_to leads_path
        end
    end

    def show
        @lead = Lead.find(params[:id])
    end

    def edit
        @lead = Lead.find(params[:id])
    end

    def update 
        lead = Lead.find(params[:id])
        lead.update(lead_params)
        redirect_to lead
        flash[:success] = "Your lead was edited!"
    end
    
    def destroy 
        lead = Lead.find(params[:id])
        lead.destroy
        redirect_to leads_path
    end

    private
    def lead_params
        params[:lead].permit(
            :business_name,
            :company_name, 
            :industry,
            :industry_desc,
            :g_email_1,
            :g_email_2,
            :g_phone_1,
            :g_phone_2,
            :gkeeper_name,
            :dm_phone,
            :dm_email
        )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
    def create_from_omniauth
        auth_hash = request.env["omniauth.auth"]
        authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

        # if: previously already logged in with OAuth
        if authentication.user
        user = authentication.user
        authentication.update_token(auth_hash)
        @next = root_url
        @notice = "Signed in!"
        # else: user logs in with OAuth for the first time
        else
        user = User.create_with_auth_and_hash(authentication, auth_hash)
        # you are expected to have a path that leads to a page for editing user details
        @next = edit_user_path(user)
        @notice = "User created. Please confirm or edit details"
        end

        sign_in(user)
        redirect_to @next, :notice => @notice
    end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
    before_action :require_login, only: [:index, :edit, :update, :show, :destroy]

    def index 
        @users = User.all
    end

    def edit 
        @user = User.find(params[:id])
    end

    def update 
        selected_user = User.find(params[:id])
        selected_user.update(user_params)
        redirect_to selected_user
    end

    def show 
        @user = User.find(params[:id])
    end

    def destroy 
        destroy_user = User.find(params[:id])
        destroy_user.destroy
        redirect_to users_path
    end

    private 
    def user_params
        params[:user].permit(
            :email,
            :password, 
            :first_name,
            :last_name,
            :phone_number
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/engages_helper.rb
module EngagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/engages/_form.html.erb
<%= form_with model: [lead, engage], local: true do |form| %>
    <%= form.submit %>
<% end %>

app/views/engages/new.html.erb
<h1>New Engage</h1>

<%= render partial: 'form', :locals => { lead: @lead ,engage: @engage } %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<hr>
<h3><%= link_to "Add Leads", new_lead_path %></h3>

<hr>
<div>
    <%= link_to "Users", users_path %>
</div>
<div>
    <%= link_to "Leads", leads_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= "signed in as #{current_user.email}"%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
      <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= link_to "Home", root_path %> 
  <%= yield %>
</body>
</html>

app/views/leads/_form.html.erb
<%= form_with model: @lead, local: true do |form| %>
    <div class="text-field">
        <%= form.label :business_name %>
        <%= form.text_field :business_name %>
    </div>
    
    <div class="text-field">
        <%= form.label :company_name %>
        <%= form.text_field :company_name %>
    </div>


    <div class="text-field">
        <%= form.label :industry %>
        <%= form.text_field :industry %>
    </div>


    <div class="text-field">
        <%= form.label :industry_description %>
        <%= form.text_field :industry_desc %>
    </div>

    <div class="text-field">
        <%= form.label :gatekeeper %>
        <%= form.text_field :gkeeper_name %>
    </div>

    <div class="text-field">
        <%= form.label :general_email_1 %>
        <%= form.text_field :g_email_1, type: "email" %>
    </div>

    <div class="text-field">
        <%= form.label :general_email_2 %>
        <%= form.text_field :g_email_2, type: "email" %>
    </div>

    <div class="text-field">
        <%= form.label :general_phone_1 %>
        <%= form.text_field :g_phone_1 %>
    </div>

    <div class="text-field">
        <%= form.label :general_phone_2 %>
        <%= form.text_field :g_phone_2 %>
    </div>


    <div class="text-field">
        <%= form.label :decision_maker_name %>
        <%= form.text_field :dm_name %>
    </div>

    <div class="text-field">
        <%= form.label :decision_maker_phone_number %>
        <%= form.text_field :dm_phone %>
    </div>

    <div class="text-field">
        <%= form.label :decision_maker_email %>
        <%= form.text_field :dm_email, type: "email" %>
    </div>
    
    <%= form.submit %>
<% end %>

app/views/leads/edit.html.erb
<h3>Edit Lead</h3>

<%= render partial: 'form' %>

app/views/leads/index.html.erb
<h1>Index Leads</h1>

<hr>

<div>
    <% @leads.each do |lead| %>
        <%= link_to "#{lead.company_name}", lead_path(lead) %> <br>
    <% end %>
</div>

app/views/leads/new.html.erb
<h3>Add New Lead</h3>

<%= render partial: 'leads/form' %>

app/views/leads/show.html.erb
<h2> Lead Details </h2>
<h4>Created by <%= link_to "#{@lead.user.first_name} #{@lead.user.last_name}", user_path(@lead.user) %></h4>

<div>
    <p> Company : <%= "#{@lead.business_name}".present? ? @lead.business_name : "nil" %></p>
    <p> Company : <%= "#{@lead.company_name}".present? ? @lead.company_name : "nil" %></p>
    <p> Industry : <%= "#{@lead.industry}".present? ? @lead.industry : "nil" %></p>
    <p> Industry Description : <%= "#{@lead.industry_desc}".present? ? @lead.industry_desc : "nil" %></p>
    <p> GateKeeper : <%= "#{@lead.gkeeper_name}".present? ? @lead.gkeeper_name : "nil" %></p>
    <p> General Email 1 : <%= "#{@lead.g_email_1}".present? ? @lead.g_email_1 : "nil" %></p>
    <p> General Email 2 : <%= "#{@lead.g_email_2}".present? ? @lead.g_email_2 : "nil" %></p>
    <p> General Phone 1 : <%= "#{@lead.g_phone_1}".present? ? @lead.g_phone_1 : "nil" %></p>
    <p> General Phone 2 : <%= "#{@lead.g_phone_2}".present? ? @lead.g_phone_2 : "nil" %></p>
    <p> Decision Maker Name : <%= "#{@lead.dm_name}".present? ? @lead.dm_name : "nil" %></p>
    <p> Decision Maker Phone Number : <%= "#{@lead.dm_phone}".present? ? @lead.dm_phone : "nil" %></p>
    <p> Decision Maker Email :<%= "#{@lead.dm_email}".present? ? @lead.dm_email : "nil" %></p>
</div>

<div>
    <% if @lead.engage == nil %>
        <%= link_to "New Engage", new_lead_engage_path(params[:id]) %>
    <% else %>
        <%= link_to "Delete Engage", lead_engage_path(lead_id: params[:id], id: current_user.id), method: :delete %>
    <% end %>
</div>
<br>
<%= link_to "Edit Lead", edit_lead_path(@lead) %>
<%= link_to "Index Lead", leads_path %>
<%= link_to "Delete Lead", lead_path(@lead), method: :delete %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
</div>

<div class="text-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
</div>

<div class="text-field">
  <%= form.label :phone_number %>
  <%= form.text_field :phone_number %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_with model: @user, local: true do |form| %>
    <div>
        <%= render partial: "/users/form", object: form %>
        <%= form.submit "Update Profile" %>
    </div>
<% end %>

app/views/users/index.html.erb
<h1> User Index </h1>
<hr>
<div>
    <% @users.each do |user| %>
        <%= link_to "#{user.first_name} #{user.last_name}", user_path(user.id) %> <br>
    <% end %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="password-field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Show User</h1>

<p>Name : <%= "#{@user.first_name} #{@user.last_name}"%></p>
<p>Email : <%= "#{@user.email}"%></p>
<p>Phone Number : <%= "#{@user.phone_number}" %></p>

<%= link_to "Index User", users_path %>
<%= link_to "Edit User", edit_user_path( @user ) %>
<%= link_to "Delete User", user_path(@user), method: :delete %>